### ISSUE TITLE
Tutorials for Ember 2.0

### ISSUE THREAD

**Issue by brentschooley** [emberwatch/emberwatch#117]
Here are a few tutorials I recently wrote:
[Getting Started With Ember.js 2.0 Using Ember CLI](https://www.twilio.com/blog/2015/08/getting-started-with-ember-js-2-0-using-ember-cli.html)
[Using Ember Data With Firebase](https://www.twilio.com/blog/2015/09/using-ember-data-with-firebase.html)

**Comment by greyhwndz** [comment]
@brentschooley Great! Will be adding them now :+1: Thanks!
