### ISSUE TITLE
Tutorial for tracking table selections

### ISSUE THREAD

**Issue by jonblack** [emberwatch/emberwatch#203]
I've written a tutorial for tracking selections in a table: http://blog.humblecoder.com/track-table-selections-in-ember/. I think it would be useful to add this to the tutorials list.

**Comment by pootsbook** [comment]
Hey @jonblack, it looks like @greyhwndz managed to add it to the tutorials list just over a week ago in dd644d920 :smiley:.

**Comment by jonblack** [comment]
@pootsbook Not quite. That was a post about model-based sidebars, and this one is about tracking table selections :)

**Comment by pootsbook** [comment]
Ah, so sorry, too early in the morning!

**Comment by jonblack** [comment]
Nice, thanks.
