### ISSUE TITLE
Migrate CSS code over to LESS / SASS

### ISSUE THREAD

**Issue by nabilfreeman** [emberwatch/emberwatch#36]
Primary benefits:
- Hierarchical CSS saves a LOT of time (nested statements)
- saves time when writing out `-webkit-transform`, `-moz-transform` etc.

The Foundation SASS file was a complete joke in regards to how much crap it packed in and ours not have all that stuff. 

Output CSS would look exactly like it does right now.

**Comment by pootsbook** [comment]
Agree. Let's go for Sass because of Jekyll / GitHub Pages native integration. See the [Jekyll Sass Docs](http://jekyllrb.com/docs/assets/#sassscss).

**Comment by nabilfreeman** [comment]
#38

**Comment by nabilfreeman** [comment]
(SCSS is SASS)

**Comment by nabilfreeman** [comment]
closed by #38
