### ISSUE TITLE
Require jekyll installation in Setup

### ISSUE THREAD

**Issue by greyhwndz** [emberwatch/emberwatch#45]
Would a setup to:

```
$ gem install jekyll
```

be required on Setup?
I tried the 3 lines in setup and realized I was missing the one I am suggesting above

**Comment by pootsbook** [comment]
Correct, those instructions assume Jekyll is installed, but that is probably unfair.

**Comment by greyhwndz** [comment]
ok thanks @pootsbook for clarifying :+1:
