### ISSUE TITLE
Recipe or blog post? Ember.js components for static sites

### ISSUE THREAD

**Issue by bf4** [emberwatch/emberwatch#72]
- http://www.benjaminfleischer.com/ember-sprinkling-in-components/
- http://www.benjaminfleischer.com/ember-cli-components/

**Comment by pootsbook** [comment]
Thanks @bf4 :+1: 

I've included them now as tutorial entries, however they might be a good fit for recipes. If you feel up to the task of formatting appropriately (see the `_recipes` folder, which is a Jekyll Collection) then I'd be more than happy to integrate.
