### ISSUE TITLE
Talks from July 22, 2015 doesn't have links to videos

### ISSUE THREAD

**Issue by greyhwndz** [emberwatch/emberwatch#76]
@pootsbook, the following talks from July 22, 2015 seems to have lost their video links:
- Custom Computed Property Macros
- Taming Content Editable with Ember
- Ember Considered Harmful

https://github.com/emberwatch/emberwatch/blob/804ab6799313ed8e85cea9e72f1a8fd39cd0fdc1/_data/talks.yml#L55

**Comment by greyhwndz** [comment]
including these:
- 14 May 2015 - SMIFF Music
- 30 Apr 2015 - Ember CLI and Super Easy™ Heroku Deployments
- 21 May 2014 - Box2D with Javascript: a practical introduction to 2d physics on the web

**Comment by pootsbook** [comment]
- SMIFF Music "[Video Coming Soon](http://emberlondon.com/)"
- Ember CLI and Super Easy ™ Heroku Deployments
- Box2D with Javascript "[Video Coming Soon](http://emberlondon.com/)"

The others I will sort out separately, they actually do have videos up on YouTube.

**Comment by greyhwndz** [comment]
@pootsbook Couldn't help it so I searched the first three missing videos and added it 

---

update: whoa! didn't notice your changes @pootsbook! :(
great thing anyway! :D
